services:
  selfmodifai:
    build: .
    environment:
      - HF_TOKEN
      - LLAMA2_HF_ENDPOINT
    volumes:
      - model:/selfmodifai/model
      - prompts:/selfmodifai/prompts
volumes:
  model:
  prompts: