services:
  selfmodifai:
    build: .
    environment:
      - OPENAI_API_KEY
      - SELFMODIFAI_GH_PAT
    volumes:
      - model:/selfmodifai/model
      - prompts:/selfmodifai/prompts
volumes:
  alpaca-lora:
  prompts: