services:
  selfmodifai-gpt4:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: selfmodifai-gpt4
    environment:
      - OPENAI_API_KEY
      - SELFMODIFAI_GH_PAT
    volumes:
      - alpaca-lora:/selfmodifai/selfmodifai-alpaca-lora
      - prompts:/selfmodifai/prompts
volumes:
  alpaca-lora:
  prompts: